# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ac2390c8a3b870feafbab603392c37c3283a47b11d417370629ce1245e5de220a619d444b6831441de55ce5fa54d7c1316db2a92a2843facb720d614593986

test:
  secret_key_base: 855f536ddc1930fc1cc5ca02b4edc00d42a7083ef1274c7389475b7c3bf2baa5227d260c8ce8d5a74e3da75183683bedd4ebad21d9bf6300b441e442019feb2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
